title: linux-aguai
description: wiki for aguai
show_chat: true
show_downloads: false
git_branch: master
logo_url: https://github.com/aguaiyoung/aguaiyoung.github.io/blob/master/logo.png?raw=true
google_analytics: true
theme: 
wiki_folder: wiki
use_github_wiki: false
use_prose_io: true
google_cse_token: 
custom_head: false
custom_sidebar: false
custom_footer: false
gems:
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-feed
deploy:
    type: git
    repo:
      github: git@github.com:aguaiyoung.github.io
      coding: git@git.coding.net:aguaiyoung,master
